### PR TITLE
fix: dynamic row navigation link

### PR DESCRIPTION
**Pull request by malkmaneth**
## Related Issue
Fixed the navigation link to dynamic rows. #62

## Motivation and Context

The button should correctly navigate to the right page for DynamicRows, instead of returning an error 404 page.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jeff-matthews — CHANGES_REQUESTED** [review]
Thanks for the PR @malkmaneth!

It looks like you updated the `package-lock.json` file though. Would you mind reverting that change so that the only changed file is `src/data/navigation/sections/ui_components.js`?

**Comment by malkmaneth** [comment]
Hi @jeff-matthews! Apologies for that, I've just reverted the ```package-log.json``` file. Thanks for 

> Thanks for the PR @malkmaneth!
> 
> It looks like you updated the `package-lock.json` file though. Would you mind reverting that change so that the only changed file is `src/data/navigation/sections/ui_components.js`?
Got it! Thanks for pointing that out 🙏

**Comment by malkmaneth** [comment]
> @malkmaneth, please also sign the Adobe CLA.

Signed! 👍

**Comment by jeff-matthews** [comment]
@malkmaneth, it looks like the Adobe CLA check still hasn't cleared. Are you sure you signed it?

**Comment by malkmaneth** [comment]
> @malkmaneth, it looks like the Adobe CLA check still hasn't cleared. Are you sure you signed it?

Hmm, I definitely did. The signed pdf and the audit log were sent to me, so I could send the transaction ID here if needed.

**Comment by jeff-matthews** [comment]
Hmmm, sometimes the check behaves in unexpected ways. Maybe it needs some more time.

**Pull request merged**
