### PR TITLE
Update email-migration.md

### PR DESCRIPTION
**Pull request by danieluniform**
There is a fault in the given example - Magento is not accepting underscores in the directive name and it causes it to fail. In the hope this will save hours of other customers time, I'm suggesting that this either gets fixed or the documentation updated as soon as possible.

## Purpose of this pull request

This pull request (PR) will fix the documentation so that it does not use underscores in the directive name. Which from my own experience does not support.

## Affected pages

- [...](https://developer.adobe.com/commerce/frontend-core/guide/templates/email-migration/#)

### CODE REVIEW

**Comment by jeff-matthews** [comment]
Thanks @danieluniform. Please sign the Adobe CLA so we can get this merged and published.

**Comment by danieluniform** [comment]
I have signed CLA. Closed PR and reopening. I assume I'm waiting for validation to come through as it's currently not possible to merge through.

image

**Comment by danieluniform** [comment]
Hey Jeff,

I already signed it but I'm still unable to merge. (I already closed,
reopened, but still failing).

Something appears wrong with the signing process. I can try again later.

Cheers,
Daniel.

**Comment by danieluniform** [comment]
@jeff-matthews Adobe CLA signed

**Comment by jeff-matthews** [comment]
Thanks @danieluniform! Sorry about that. Unfortunately, the CLA check is notoriously buggy. This will auto-merge as soon as the validation check finishes running.

**Pull request merged**
