### PR TITLE
Upgrade theme to v4.11.9

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) upgrades theme to [v4.11.9](https://github.com/adobe/aio-theme/compare/%40adobe/gatsby-theme-aio%404.11.3...%40adobe/gatsby-theme-aio%404.11.9).

Jira: COMDOX-913

## Preview

https://developer-stage.adobe.com/commerce/frontend-core/

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Comment by dshevtsov** [comment]
Trying to reproduce locally

**Comment by dshevtsov** [comment]
No issues locally

**Comment by dshevtsov** [comment]
Removal of GH caches didn't help

**Comment by dshevtsov** [comment]
In contrast, the staging workflow is not failing. Investigating.

**Pull request merged**
