### PR TITLE
COMDOX-114: Migrate Page Builder from Magento/pagebuilder-docs

### PR DESCRIPTION
**Pull request by jhadobe**
### Purpose of this pull request

This pull request (PR) migrates [Page Builder](https://devdocs.magento.com/page-builder/docs/index.html) from the devdocs.magento.com site to the Adobe DevSite.

Staging: https://developer-stage.adobe.com/commerce/frontend-core/page-builder/

### Affected pages
Several

### Links to related PRs or Jira tickets
https://jira.corp.adobe.com/browse/COMDOX-114
https://github.com/magento/pagebuilder-docs/ (coming soon)

(there are 2 open PRs in the old repo: https://github.com/magento/pagebuilder-docs)

### Notes for reviewer:
- Since I can't add an external top-level link in the toc, I created a redirect for the [Release Notes](https://developer-stage.adobe.com/commerce/frontend-core/page-builder/release-notes/) page. I used `window.location.href` because `window.location.replace` didn't work for some reason.
- Many images have captions under them. Previously they had an up arrow pointing at the image. I removed it, but left the captions. They may need to be removed entirely since I don't think the aio-theme has a good way of handling them.
-  I removed number two from [this summary](https://devdocs.magento.com/page-builder/docs/viewports/introduction.html#summary) because the page hasn't been edited in 19 months. 
-  The first two steps in [this section](https://devdocs.magento.com/page-builder/docs/architecture/overview.html#data-flow) had empty sets () in them, so I removed them. I assume they are remnants of removed links.
-  There is a dreaded contentless overview [page here](https://developer-stage.adobe.com/commerce/frontend-core/page-builder/content-types/). An index file was required and there were only three subfolders in the content-types folder, so this seemed like an acceptable solution.

### CODE REVIEW

**Comment by jhadobe** [comment]
> @jhadobe and @jeff-matthews:
> 
> For now, let's favor the user experience over maintenance and remove the Release notes auto-redirect link from the left-side navigation. I know it duplicates the release notes that were added to the Page Builder user guide hosted in Experience League. But those release notes where here first! Kidding. The reason I think it's best to maintain two copies right now (until we come up with a better solution for importing the same source into both sites) is to keep the user experience stable and consistent.
> 
> To better communicate the harm caused by the redirection, in the current absence of a better solution, I recorded a short user-experience test of the issue:
> 
> https://vimeo.com/758545567
> 
> I'll finish the rest of the review and approve it today.

great video @bdenham. Alternatively, we could just have a landing page with some brief explanation explaining that the PB release notes are on another site and have a link that opens in a new tab/window. i'm not aware of a way to force a link to open in a new tab from the TOC, but i think the new tab experience would leave less room for confusion.

**Comment by jeff-matthews** [comment]
Haha! Love the video @bdenham. It showcases valid issues in a fun way.

Duplicating the releases notes presents another potential UX issue though. What happens to trust if/when the release notes on the devsite don't match what's in ExL? What happens if the release notes on the devsite don't contain the latest release? 

Duplicating the notes (right now) relies on human intervention to ensure that the latest content is published in the devsite _and_ ExL. Based on my experience relying on humans in these types of scenarios, that's risky. In other words, I think it's probable that the notes will diverge between sites.

What do you think about @jhadobe's proposed compromise?

**Comment by jhadobe** [comment]
@bdenham @jeff-matthews another alternative is listing this in the TOC as a subpage (which will open in a new tab). the only complication is that the page above it in the hierarchy requires a local path, which is not ideal.

in this image, clicking "Release notes" takes you to `/page-builder/index`, but clicking "Release notes (on Experience League)" opens the correct link in a new tab.

2nd level

**Comment by bdenham** [comment]
@jhadobe and @jeff-matthews, yeah, so I think the first option you mentioned, @jhadobe, is best for now. I still think it's ok to duplicate the release notes _temporarily_, — until we solve the single-source problem across repos (within the same platform) and then across platforms (between Gatsby and ExL). 

I want to solve this problem in Q4, but I certainly understand the push to deduplicate the content now. So I'm good with making the Release notes link open a standard page called Release notes and then explicitly providing a link to the Experience League release notes with a brief explanation for why we're linking to the shared release notes within the Page Builder User Guide. I can live with that solution until we put the final solution in place. 👍

**Review by bdenham — APPROVED** [review]
Approved pending removal of auto-redirect link to Release notes.

**Comment by jeff-matthews** [comment]
Sounds good @bdenham. I'll create a COMDOX ticket for this so we don't lose track.

**Pull request merged**
